[project]
name = "tp-programacion-unaj-maestria"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jupyterlab>=4.4.2",
    "pandas>=2.2.3",
    "ruff>=0.11.10",
    "tabulate>=0.9.0",
]
